# Generated by Django 3.2.8 on 2021-10-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0002_auto_20211031_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('payment', models.BooleanField(default=False)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.year')),
            ],
        ),
    ]
