# Generated by Django 3.2.8 on 2021-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_info_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
